import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Small Next.js Portfolio',
  description: 'Generated by Next.js + Sanity.io',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}
      </body>
    </html>
  )
}
