import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Small Next.js Portfolio',
  description: 'Generated by Next.js + Sanity.io',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className + "max-w-3xl mx-auto p-10"}>
        <header>
          <Link href="/" className="bg-gradient-to-r from-amber-400 via-purple-500 to bg-red-400 bg-clip-text text-transparent text-lg font-bold">
            Timur
          </Link>
        </header>
        <main className="py-20">
        {children}
        </main>
      </body>
    </html>
  )
}
