import { getPages } from '@/sanity/sanity-utils';
import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Small Next.js Portfolio',
  description: 'Generated by Next.js + Sanity.io',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pages = await getPages();
  
  return (
    <html lang="en">
      <body className='max-w-4xl mx-auto p-10'>
        <header className="flex items-center justify-between">
          <Link
            href="/"
            className="bg-gradient-to-r from-amber-400 via-purple-500 to bg-red-400 bg-clip-text text-transparent text-lg font-bold"
          >
            Timur
          </Link>
          <div className="flex items-center gap-5 text-sm text-slate-200">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}

